# -*- coding: utf-8 -*-
"""Practical_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k86frQxnuKQFIjbXXN3Zf_HdhEmAWPYR
"""

n = int(input("Enter number of machines: "))

machines = []
q_values = []

for i in range(n):
    name = input("Enter machine name: ")
    rewards = list(map(int, input("Enter rewards: ").split()))

    q = sum(rewards) / len(rewards)

    machines.append(name)
    q_values.append(q)

    print("Machine", name)
    print("Rewards:", rewards)
    print("Q(" + name + ") =", q)
highest = q_values.index(max(q_values))

print("Greedy Selected Machine:", machines[highest])

n = int(input("Enter number of machines: "))

machines = []
Q = []
N = []

for i in range(n):
    name = input("Enter machine name: ")
    rewards = list(map(int, input("Enter rewards: ").split()))

    machines.append(name)
    Q.append(0)
    N.append(0)

    for reward in rewards:
        N[i] = N[i] + 1

        Q[i] = Q[i] + (reward - Q[i]) / N[i]

    print("Machine", name)
    print("Rewards:", rewards)
    print("Q(" + name + ") =", Q[i])
index = Q.index(max(Q))

print("Greedy Selected Machine:", machines[index])