# -*- coding: utf-8 -*-
"""practical_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_x0wKfXcIJ7yeMq-3geP-Hin0uQdtR6c
"""

import random


machines = ['A', 'B', 'C']

rewards = {
    'A': [3, 4, 2, 5],
    'B': [6, 7, 5, 8],
    'C': [4, 3, 5, 4]
}

N = [0, 0, 0]
R = [0, 0, 0]
Q = [0, 0, 0]

epsilon = 0.2

reward_index = [0, 0, 0]

total_reward = 0

# 10 plays
for play in range(1, 11):

    r = random.random()

    if r < epsilon:

        index = random.randint(0, 2)
        print("\nPlay", play, ": Exploration")

    else:

        index = Q.index(max(Q))
        print("\nPlay", play, ": Exploitation")

    machine = machines[index]

    print("Selected Machine:", machine)

    reward = rewards[machine][reward_index[index] % 4]

    reward_index[index] = reward_index[index] + 1

    print("Reward:", reward)

    N[index] = N[index] + 1

    R[index] = R[index] + reward

    Q[index] = Q[index] + (reward - Q[index]) / N[index]

    total_reward = total_reward + reward

    print("N:", N)
    print("R:", R)
    print("Q:", Q)

print("\n----- FINAL RESULTS -----")

print("Machine\tN\tR\tQ")

for i in range(3):
    print(machines[i], "\t", N[i], "\t", R[i], "\t", round(Q[i], 2))

print("\nTotal Reward after 10 plays:", total_reward)